version: '3.9'

services:
  alpined:
    build:
      context: .
      dockerfile: Dockerfile-02

    container_name: alpined
    ports:
      - "21022:22"
      - "21023:21023"
      - "8088:80"
    volumes:
      - alpine_data:/var/www/html
    networks:
      net_work:
        ipv4_address: 172.20.0.2

networks:
  net_work:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  alpine_data:
