FROM alpine:latest

# Set environment variables (replace password with your desired one)
ENV USERNAME c
ENV PASSWORD 22111357 


RUN apk add --no-cache openrc openssh 

# RUN apk add --no-cache nginx 

RUN adduser -D -s /bin/bash $USERNAME && \
    echo "$USERNAME:$PASSWORD" | chpasswd

# Configure SSH (replace ports with your desired values)
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    sed -i 's/Port 22/Port 21022/' /etc/ssh/sshd_config && \
    echo "Port 21023" >> /etc/ssh/sshd_config

# Expose ports
EXPOSE 21022 21023 8088

# Persist data volume (adjust if needed)
VOLUME /var/www/html

# Start SSH daemon
CMD ["rc-service", "sshd", "start"]

# Optional: Start Nginx web server (uncomment if needed)
# CMD ["nginx", "-g", "daemon off;"]
